# Generated by Django 3.2.8 on 2021-12-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turmas.turma')),
            ],
        ),
    ]
