# Generated by Django 3.2.8 on 2021-11-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professores',
            new_name='Professor',
        ),
    ]
