# Generated by Django 3.2.8 on 2021-11-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_rename_professores_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='nomeFoto',
            new_name='foto',
        ),
    ]
