# Generated by Django 3.2.8 on 2021-11-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_rename_nomefoto_professor_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AddField(
            model_name='professor',
            name='matricula',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
