# Generated by Django 3.2.8 on 2021-11-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_auto_20211115_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titularidade',
            fields=[
                ('codigo', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='titularidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='professores.titularidade'),
            preserve_default=False,
        ),
    ]
