# Generated by Django 3.2.8 on 2021-11-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0005_auto_20211117_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titularidade',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
