# Generated by Django 3.2.8 on 2021-12-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0007_alter_professor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
