# Generated by Django 3.2.8 on 2021-12-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0008_alter_professor_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='foto',
        ),
    ]
