# Generated by Django 3.2.8 on 2021-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0010_professor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/% Y/% m/% d/'),
        ),
    ]
