# Generated by Django 3.2.8 on 2021-12-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0011_alter_professor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='publicar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
