# Generated by Django 3.2.8 on 2021-11-17 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0004_auto_20211115_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=10)),
                ('sala', models.IntegerField()),
                ('horaInicial', models.TimeField(default=django.utils.timezone.now)),
                ('horaFinal', models.TimeField(default=django.utils.timezone.now)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professores.professor')),
            ],
        ),
    ]
